### PR TITLE
Remove async interrupt

### PR DESCRIPTION
**Pull request by dewert99**
I noticed that the `Solver::interrupt_async` isn't useful since `Solver::solve_limited` requires a `&mut Solver`. Rust's aliasing restrictions make it impossible to (soundly) have a shared reference to a `Solver` that is running `solve_limited` in another thread. An asynchronous update would be possible using and `Arc<AtomicBool>` or `&AtomicBool` but this could implemented using `Callbacks` so I don't think this would be needed in the `Solver` struct anyway.
```rust
struct AsyncInterrupt(Arc<AtomicBool>);

impl Callbacks for AsyncInterrupt {
    fn stop(&self) -> bool {
        self.0.load(Ordering::SeqCst)
    }
}

fn solve_with_timeout(solver: &mut Solver<AsyncInterrupt>, timeout: Duration) {
    solver.cb().0.store(false, Ordering::SeqCst);
    let interrupt = solver.cb().0.clone();
    std::thread::spawn(move || {
        std::thread::sleep(timeout);
        interrupt.store(true, Ordering::SeqCst)
    });
    solver.solve_limited(&[]);
}
```

### CODE REVIEW

**Comment by c-cube** [comment]
Makes sense. It'd be nice to have an alternative using `Arc<AtomicBool>` (possibly with callbacks that use that atomic bool to stop the solving) but this might be too much for this PR.

**Comment by dewert99** [comment]
If you think it would be helpful I could add:
```rust
pub struct AsyncInterrupt(Arc<AtomicBool>);

pub struct AsyncInterruptHandle(Arc<AtomicBool>);

impl Callbacks for AsyncInterrupt {
    fn on_start(&mut self) {
        self.0.store(false, Ordering::SeqCst)
    }
    fn stop(&self) -> bool {
        self.0.load(Ordering::SeqCst)
    }
}

impl Default for AsyncInterrupt {
    fn default() -> Self {
        AsyncInterrupt(Arc::new(AtomicBool::new(false)))
    }
}

impl AsyncInterrupt {
    pub fn get_handle(&self) -> AsyncInterruptHandle {
        AsyncInterruptHandle(self.0.clone())
    }
}

impl AsyncInterruptHandle {
    pub fn interrupt_async(&self) {
        self.0.store(true, Ordering::SeqCst)
    }
}
```

**Comment by c-cube** [comment]
That would be very nice, thank you! :)

**Comment by c-cube** [comment]
Perfect, thank you!

**Pull request merged**
